GridInject += GridInject_data.o \
	gi_interface.o gi_distance.o gi_distanceVector.o gi_normal_rand.o gi_overlap.o
#GridInject_init.o : GridInject_data.o
#GridInject_thermalSN.o : gi_distance.o
#GridInject_kineticSN.o : gi_overlap.o
#GridInject_wind.o : GridInject_data.o gi_overlap.o gi_normal_rand.o
