#  Makefile for the initialization section of the Particles module 
# [source/Particles/ParticlesMain/ray]

Particles += pt_rayInterface.o pt_generateRaysFace.o pt_advanceRaysFace.o \
						pt_generateRaysPoint.o pt_advanceRaysPoint.o pt_startComm.o

