# Makefile for the Legacy Sink RT module.

RadTrans += RadTrans_RayTrace_Sink.o

RadTrans_RayTrace_Sink.o : tree.o \
				Logfile_interface.o \
				Driver_data.o \
				Grid_data.o \
				raytrace_data.o \
				rt_data_raytrace_3drt.o \
				rt_init_raytrace_3drt.o \
				Grid_interface.o \
				Timers_interface.o \
				RadTrans_hybridCharModule.o \
				RadTrans_CommunicateGlobalTreeData.o \
				calc_local_block_contributions_sink.o \
				calc_local_block_contrib_face_3DRT.o \
				create_cut_block_list_3DRT.o \
				healpix.o \
				Opacity_sink_interface.o \
				RadTrans_RayTrace_3DRT.o