# Makefile for the Hybrid Characteristics radiative transfer module.

RadTrans += rt_source_function_block.o  \
			RadTrans_update_source_function.o 


RadTrans_update_source_function.o : tree.o \
				Driver_data.o \
				Timers_interface.o \
				RadTrans_hybridCharModule.o \
				rt_source_function_block.o
