#  Makefile for passively advected particle drivers (Euler integrator).
# [source/Particles/timeIntegration/passive/EulerPassive]

Particles += pt_advanceMonteCarlo_data.o pt_advanceMonteCarlo_init.o
pt_advanceMonteCarlo.o : pt_advanceMonteCarlo_data.o
