Simulation += Simulation_data.o Simulation_addStaticAcceleration.o
Simulation_init.o : Simulation_data.o
Simulation_initBlock.o : Simulation_data.o
#Simulation_addStaticAcceleration.o : Simulation_data.o

Grid += gr_markInZ.o
