# Makefile for the Hybrid Characteristics radiative transfer module.

RadTrans += rt_mean_intensity_block.o \
			RadTrans_update_radiation_field.o


RadTrans_update_radiation_field.o : rt_mean_intensity_block.o 

